// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.76.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

class RustImpl implements Rust {
  final RustPlatform _platform;
  factory RustImpl(ExternalLibrary dylib) => RustImpl.raw(RustPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory RustImpl.wasm(FutureOr<WasmModule> module) =>
      RustImpl(module as ExternalLibrary);
  RustImpl.raw(this._platform);
  Future<void> initDb({required String storagePath, dynamic hint}) {
    var arg0 = _platform.api2wire_String(storagePath);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_init_db(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kInitDbConstMeta,
      argValues: [storagePath],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitDbConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "init_db",
        argNames: ["storagePath"],
      );

  Future<String> initNostr(
      {required String storagePath, String? privateKey, dynamic hint}) {
    var arg0 = _platform.api2wire_String(storagePath);
    var arg1 = _platform.api2wire_opt_String(privateKey);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_init_nostr(port_, arg0, arg1),
      parseSuccessData: _wire2api_String,
      constMeta: kInitNostrConstMeta,
      argValues: [storagePath, privateKey],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitNostrConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "init_nostr",
        argNames: ["storagePath", "privateKey"],
      );

  Future<KeyData?> getKeys({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_keys(port_),
      parseSuccessData: _wire2api_opt_box_autoadd_key_data,
      constMeta: kGetKeysConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetKeysConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_keys",
        argNames: [],
      );

  Future<void> nostrLogout({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_nostr_logout(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kNostrLogoutConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kNostrLogoutConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "nostr_logout",
        argNames: [],
      );

  Future<List<String>> getRelays({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_relays(port_),
      parseSuccessData: _wire2api_StringList,
      constMeta: kGetRelaysConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetRelaysConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_relays",
        argNames: [],
      );

  Future<void> addRelay({required String relay, dynamic hint}) {
    var arg0 = _platform.api2wire_String(relay);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_add_relay(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kAddRelayConstMeta,
      argValues: [relay],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAddRelayConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "add_relay",
        argNames: ["relay"],
      );

  Future<void> removeRelay({required String relay, dynamic hint}) {
    var arg0 = _platform.api2wire_String(relay);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_remove_relay(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kRemoveRelayConstMeta,
      argValues: [relay],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRemoveRelayConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "remove_relay",
        argNames: ["relay"],
      );

  Future<List<Contact>> fetchContacts({required String pubkey, dynamic hint}) {
    var arg0 = _platform.api2wire_String(pubkey);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_fetch_contacts(port_, arg0),
      parseSuccessData: _wire2api_list_contact,
      constMeta: kFetchContactsConstMeta,
      argValues: [pubkey],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kFetchContactsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "fetch_contacts",
        argNames: ["pubkey"],
      );

  Future<void> addContact({required String pubkey, dynamic hint}) {
    var arg0 = _platform.api2wire_String(pubkey);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_add_contact(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kAddContactConstMeta,
      argValues: [pubkey],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAddContactConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "add_contact",
        argNames: ["pubkey"],
      );

  Future<void> removeContact({required String pubkey, dynamic hint}) {
    var arg0 = _platform.api2wire_String(pubkey);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_remove_contact(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kRemoveContactConstMeta,
      argValues: [pubkey],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRemoveContactConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "remove_contact",
        argNames: ["pubkey"],
      );

  Future<List<Contact>> getContacts({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_contacts(port_),
      parseSuccessData: _wire2api_list_contact,
      constMeta: kGetContactsConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetContactsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_contacts",
        argNames: [],
      );

  Future<String?> getContactPictureId({required String pubkey, dynamic hint}) {
    var arg0 = _platform.api2wire_String(pubkey);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_get_contact_picture_id(port_, arg0),
      parseSuccessData: _wire2api_opt_String,
      constMeta: kGetContactPictureIdConstMeta,
      argValues: [pubkey],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetContactPictureIdConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_contact_picture_id",
        argNames: ["pubkey"],
      );

  Future<String> fetchPicture({required String url, dynamic hint}) {
    var arg0 = _platform.api2wire_String(url);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_fetch_picture(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kFetchPictureConstMeta,
      argValues: [url],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kFetchPictureConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "fetch_picture",
        argNames: ["url"],
      );

  Future<Conversation> sendMessage(
      {required String pubkey, required Message message, dynamic hint}) {
    var arg0 = _platform.api2wire_String(pubkey);
    var arg1 = _platform.api2wire_box_autoadd_message(message);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_send_message(port_, arg0, arg1),
      parseSuccessData: _wire2api_conversation,
      constMeta: kSendMessageConstMeta,
      argValues: [pubkey, message],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSendMessageConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "send_message",
        argNames: ["pubkey", "message"],
      );

  Future<Conversation> getConversation({required String pubkey, dynamic hint}) {
    var arg0 = _platform.api2wire_String(pubkey);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_conversation(port_, arg0),
      parseSuccessData: _wire2api_conversation,
      constMeta: kGetConversationConstMeta,
      argValues: [pubkey],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetConversationConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_conversation",
        argNames: ["pubkey"],
      );

  Future<String> getBalances({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_balances(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kGetBalancesConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetBalancesConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_balances",
        argNames: [],
      );

  Future<void> addMint({required String url, dynamic hint}) {
    var arg0 = _platform.api2wire_String(url);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_add_mint(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kAddMintConstMeta,
      argValues: [url],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAddMintConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "add_mint",
        argNames: ["url"],
      );

  Future<List<String>> getWallets({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_wallets(port_),
      parseSuccessData: _wire2api_StringList,
      constMeta: kGetWalletsConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetWalletsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_wallets",
        argNames: [],
      );

  Future<String> removeWallet({required String url, dynamic hint}) {
    var arg0 = _platform.api2wire_String(url);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_remove_wallet(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kRemoveWalletConstMeta,
      argValues: [url],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRemoveWalletConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "remove_wallet",
        argNames: ["url"],
      );

  Future<TransactionStatus> checkSpendable(
      {required Transaction transaction, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_transaction(transaction);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_check_spendable(port_, arg0),
      parseSuccessData: _wire2api_transaction_status,
      constMeta: kCheckSpendableConstMeta,
      argValues: [transaction],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCheckSpendableConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "check_spendable",
        argNames: ["transaction"],
      );

  Future<Transaction> receiveToken(
      {required String encodedToken, dynamic hint}) {
    var arg0 = _platform.api2wire_String(encodedToken);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_receive_token(port_, arg0),
      parseSuccessData: _wire2api_transaction,
      constMeta: kReceiveTokenConstMeta,
      argValues: [encodedToken],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kReceiveTokenConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "receive_token",
        argNames: ["encodedToken"],
      );

  Future<Transaction> send(
      {required int amount, required String activeMint, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(amount);
    var arg1 = _platform.api2wire_String(activeMint);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_send(port_, arg0, arg1),
      parseSuccessData: _wire2api_transaction,
      constMeta: kSendConstMeta,
      argValues: [amount, activeMint],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSendConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "send",
        argNames: ["amount", "activeMint"],
      );

  Future<Transaction> requestMint(
      {required int amount, required String mintUrl, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(amount);
    var arg1 = _platform.api2wire_String(mintUrl);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_request_mint(port_, arg0, arg1),
      parseSuccessData: _wire2api_transaction,
      constMeta: kRequestMintConstMeta,
      argValues: [amount, mintUrl],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRequestMintConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "request_mint",
        argNames: ["amount", "mintUrl"],
      );

  Future<void> mintToken(
      {required int amount,
      required String hash,
      required String mint,
      dynamic hint}) {
    var arg0 = _platform.api2wire_u64(amount);
    var arg1 = _platform.api2wire_String(hash);
    var arg2 = _platform.api2wire_String(mint);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_mint_token(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_unit,
      constMeta: kMintTokenConstMeta,
      argValues: [amount, hash, mint],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMintTokenConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "mint_token",
        argNames: ["amount", "hash", "mint"],
      );

  Future<void> mintSwap(
      {required String fromMint,
      required String toMint,
      required int amount,
      dynamic hint}) {
    var arg0 = _platform.api2wire_String(fromMint);
    var arg1 = _platform.api2wire_String(toMint);
    var arg2 = _platform.api2wire_u64(amount);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_mint_swap(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_unit,
      constMeta: kMintSwapConstMeta,
      argValues: [fromMint, toMint, amount],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMintSwapConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "mint_swap",
        argNames: ["fromMint", "toMint", "amount"],
      );

  Future<Transaction> melt(
      {required int amount,
      required String invoice,
      required String mint,
      dynamic hint}) {
    var arg0 = _platform.api2wire_u64(amount);
    var arg1 = _platform.api2wire_String(invoice);
    var arg2 = _platform.api2wire_String(mint);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_melt(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_transaction,
      constMeta: kMeltConstMeta,
      argValues: [amount, invoice, mint],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMeltConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "melt",
        argNames: ["amount", "invoice", "mint"],
      );

  Future<InvoiceInfo> decodeInvoice(
      {required String encodedInvoice, dynamic hint}) {
    var arg0 = _platform.api2wire_String(encodedInvoice);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_decode_invoice(port_, arg0),
      parseSuccessData: _wire2api_invoice_info,
      constMeta: kDecodeInvoiceConstMeta,
      argValues: [encodedInvoice],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kDecodeInvoiceConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "decode_invoice",
        argNames: ["encodedInvoice"],
      );

  Future<List<Transaction>> getTransactions({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_transactions(port_),
      parseSuccessData: _wire2api_list_transaction,
      constMeta: kGetTransactionsConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetTransactionsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_transactions",
        argNames: [],
      );

  Future<List<Transaction>> getInbox({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_inbox(port_),
      parseSuccessData: _wire2api_list_transaction,
      constMeta: kGetInboxConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetInboxConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_inbox",
        argNames: [],
      );

  Future<void> redeamInbox({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_redeam_inbox(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kRedeamInboxConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRedeamInboxConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "redeam_inbox",
        argNames: [],
      );

  Future<Transaction?> getTransaction({required String tid, dynamic hint}) {
    var arg0 = _platform.api2wire_String(tid);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_transaction(port_, arg0),
      parseSuccessData: _wire2api_opt_box_autoadd_transaction,
      constMeta: kGetTransactionConstMeta,
      argValues: [tid],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetTransactionConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_transaction",
        argNames: ["tid"],
      );

  Future<List<Mint>> getMints({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_mints(port_),
      parseSuccessData: _wire2api_list_mint,
      constMeta: kGetMintsConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetMintsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_mints",
        argNames: [],
      );

  Future<MintInformation?> getMintInformation(
      {required String mint, dynamic hint}) {
    var arg0 = _platform.api2wire_String(mint);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_get_mint_information(port_, arg0),
      parseSuccessData: _wire2api_opt_box_autoadd_mint_information,
      constMeta: kGetMintInformationConstMeta,
      argValues: [mint],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetMintInformationConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_mint_information",
        argNames: ["mint"],
      );

  Future<Mint?> getActiveMint({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_active_mint(port_),
      parseSuccessData: _wire2api_opt_box_autoadd_mint,
      constMeta: kGetActiveMintConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetActiveMintConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_active_mint",
        argNames: [],
      );

  Future<void> setActiveMint({String? mintUrl, dynamic hint}) {
    var arg0 = _platform.api2wire_opt_String(mintUrl);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_set_active_mint(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kSetActiveMintConstMeta,
      argValues: [mintUrl],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSetActiveMintConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "set_active_mint",
        argNames: ["mintUrl"],
      );

  Future<TokenData> decodeToken({required String encodedToken, dynamic hint}) {
    var arg0 = _platform.api2wire_String(encodedToken);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_decode_token(port_, arg0),
      parseSuccessData: _wire2api_token_data,
      constMeta: kDecodeTokenConstMeta,
      argValues: [encodedToken],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kDecodeTokenConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "decode_token",
        argNames: ["encodedToken"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  List<String> _wire2api_StringList(dynamic raw) {
    return (raw as List<dynamic>).cast<String>();
  }

  CashuTransaction _wire2api_box_autoadd_cashu_transaction(dynamic raw) {
    return _wire2api_cashu_transaction(raw);
  }

  KeyData _wire2api_box_autoadd_key_data(dynamic raw) {
    return _wire2api_key_data(raw);
  }

  LNTransaction _wire2api_box_autoadd_ln_transaction(dynamic raw) {
    return _wire2api_ln_transaction(raw);
  }

  Mint _wire2api_box_autoadd_mint(dynamic raw) {
    return _wire2api_mint(raw);
  }

  MintInformation _wire2api_box_autoadd_mint_information(dynamic raw) {
    return _wire2api_mint_information(raw);
  }

  MintVersion _wire2api_box_autoadd_mint_version(dynamic raw) {
    return _wire2api_mint_version(raw);
  }

  Picture _wire2api_box_autoadd_picture(dynamic raw) {
    return _wire2api_picture(raw);
  }

  Transaction _wire2api_box_autoadd_transaction(dynamic raw) {
    return _wire2api_transaction(raw);
  }

  int _wire2api_box_autoadd_u64(dynamic raw) {
    return _wire2api_u64(raw);
  }

  CashuTransaction _wire2api_cashu_transaction(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CashuTransaction(
      id: _wire2api_opt_String(arr[0]),
      status: _wire2api_transaction_status(arr[1]),
      time: _wire2api_u64(arr[2]),
      amount: _wire2api_u64(arr[3]),
      mint: _wire2api_String(arr[4]),
      token: _wire2api_String(arr[5]),
      from: _wire2api_opt_String(arr[6]),
    );
  }

  Contact _wire2api_contact(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Contact(
      pubkey: _wire2api_String(arr[0]),
      npub: _wire2api_String(arr[1]),
      name: _wire2api_opt_String(arr[2]),
      picture: _wire2api_opt_box_autoadd_picture(arr[3]),
      lud16: _wire2api_opt_String(arr[4]),
      createdAt: _wire2api_opt_box_autoadd_u64(arr[5]),
    );
  }

  Conversation _wire2api_conversation(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Conversation(
      messages: _wire2api_list_message(arr[0]),
      transactions: _wire2api_list_transaction(arr[1]),
    );
  }

  Direction _wire2api_direction(dynamic raw) {
    return Direction.values[raw as int];
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  InvoiceInfo _wire2api_invoice_info(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return InvoiceInfo(
      bolt11: _wire2api_String(arr[0]),
      amount: _wire2api_u64(arr[1]),
      hash: _wire2api_String(arr[2]),
      memo: _wire2api_opt_String(arr[3]),
      mint: _wire2api_opt_String(arr[4]),
      status: _wire2api_invoice_status(arr[5]),
    );
  }

  InvoiceStatus _wire2api_invoice_status(dynamic raw) {
    return InvoiceStatus.values[raw as int];
  }

  KeyData _wire2api_key_data(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyData(
      npub: _wire2api_String(arr[0]),
      nsec: _wire2api_opt_String(arr[1]),
    );
  }

  List<List<String>> _wire2api_list_StringList(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_StringList).toList();
  }

  List<Contact> _wire2api_list_contact(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_contact).toList();
  }

  List<Message> _wire2api_list_message(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_message).toList();
  }

  List<Mint> _wire2api_list_mint(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_mint).toList();
  }

  List<Transaction> _wire2api_list_transaction(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_transaction).toList();
  }

  LNTransaction _wire2api_ln_transaction(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return LNTransaction(
      id: _wire2api_opt_String(arr[0]),
      status: _wire2api_transaction_status(arr[1]),
      time: _wire2api_u64(arr[2]),
      amount: _wire2api_u64(arr[3]),
      fee: _wire2api_opt_box_autoadd_u64(arr[4]),
      mint: _wire2api_opt_String(arr[5]),
      bolt11: _wire2api_String(arr[6]),
      hash: _wire2api_String(arr[7]),
    );
  }

  Message _wire2api_message(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return Message_Text(
          direction: _wire2api_direction(raw[1]),
          time: _wire2api_u64(raw[2]),
          content: _wire2api_String(raw[3]),
        );
      case 1:
        return Message_Invoice(
          direction: _wire2api_direction(raw[1]),
          time: _wire2api_u64(raw[2]),
          transactionId: _wire2api_String(raw[3]),
        );
      case 2:
        return Message_Token(
          direction: _wire2api_direction(raw[1]),
          time: _wire2api_u64(raw[2]),
          transactionId: _wire2api_String(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  Mint _wire2api_mint(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Mint(
      url: _wire2api_String(arr[0]),
      activeKeyset: _wire2api_opt_String(arr[1]),
      keysets: _wire2api_StringList(arr[2]),
      info: _wire2api_opt_box_autoadd_mint_information(arr[3]),
    );
  }

  MintInformation _wire2api_mint_information(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MintInformation(
      name: _wire2api_opt_String(arr[0]),
      pubkey: _wire2api_opt_String(arr[1]),
      version: _wire2api_opt_box_autoadd_mint_version(arr[2]),
      description: _wire2api_opt_String(arr[3]),
      descriptionLong: _wire2api_opt_String(arr[4]),
      contact: _wire2api_list_StringList(arr[5]),
      nuts: _wire2api_StringList(arr[6]),
      motd: _wire2api_opt_String(arr[7]),
    );
  }

  MintVersion _wire2api_mint_version(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MintVersion(
      name: _wire2api_String(arr[0]),
      version: _wire2api_String(arr[1]),
    );
  }

  String? _wire2api_opt_String(dynamic raw) {
    return raw == null ? null : _wire2api_String(raw);
  }

  KeyData? _wire2api_opt_box_autoadd_key_data(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_key_data(raw);
  }

  Mint? _wire2api_opt_box_autoadd_mint(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_mint(raw);
  }

  MintInformation? _wire2api_opt_box_autoadd_mint_information(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_mint_information(raw);
  }

  MintVersion? _wire2api_opt_box_autoadd_mint_version(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_mint_version(raw);
  }

  Picture? _wire2api_opt_box_autoadd_picture(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_picture(raw);
  }

  Transaction? _wire2api_opt_box_autoadd_transaction(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_transaction(raw);
  }

  int? _wire2api_opt_box_autoadd_u64(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_u64(raw);
  }

  Pending _wire2api_pending(dynamic raw) {
    return Pending.values[raw as int];
  }

  Picture _wire2api_picture(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Picture(
      url: _wire2api_String(arr[0]),
      hash: _wire2api_opt_String(arr[1]),
      updated: _wire2api_u64(arr[2]),
    );
  }

  TokenData _wire2api_token_data(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TokenData(
      encodedToken: _wire2api_String(arr[0]),
      mint: _wire2api_String(arr[1]),
      amount: _wire2api_u64(arr[2]),
      memo: _wire2api_opt_String(arr[3]),
    );
  }

  Transaction _wire2api_transaction(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return Transaction_CashuTransaction(
          _wire2api_box_autoadd_cashu_transaction(raw[1]),
        );
      case 1:
        return Transaction_LNTransaction(
          _wire2api_box_autoadd_ln_transaction(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  TransactionStatus _wire2api_transaction_status(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return TransactionStatus_Sent();
      case 1:
        return TransactionStatus_Received();
      case 2:
        return TransactionStatus_Pending(
          _wire2api_pending(raw[1]),
        );
      case 3:
        return TransactionStatus_Failed();
      case 4:
        return TransactionStatus_Expired();
      default:
        throw Exception("unreachable");
    }
  }

  int _wire2api_u64(dynamic raw) {
    return castInt(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_direction(Direction raw) {
  return api2wire_i32(raw.index);
}

@protected
int api2wire_i32(int raw) {
  return raw;
}

@protected
int api2wire_pending(Pending raw) {
  return api2wire_i32(raw.index);
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class RustPlatform extends FlutterRustBridgeBase<RustWire> {
  RustPlatform(ffi.DynamicLibrary dylib) : super(RustWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_CashuTransaction> api2wire_box_autoadd_cashu_transaction(
      CashuTransaction raw) {
    final ptr = inner.new_box_autoadd_cashu_transaction_0();
    _api_fill_to_wire_cashu_transaction(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_LNTransaction> api2wire_box_autoadd_ln_transaction(
      LNTransaction raw) {
    final ptr = inner.new_box_autoadd_ln_transaction_0();
    _api_fill_to_wire_ln_transaction(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_Message> api2wire_box_autoadd_message(Message raw) {
    final ptr = inner.new_box_autoadd_message_0();
    _api_fill_to_wire_message(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_Transaction> api2wire_box_autoadd_transaction(
      Transaction raw) {
    final ptr = inner.new_box_autoadd_transaction_0();
    _api_fill_to_wire_transaction(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Uint64> api2wire_box_autoadd_u64(int raw) {
    return inner.new_box_autoadd_u64_0(api2wire_u64(raw));
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_opt_String(String? raw) {
    return raw == null ? ffi.nullptr : api2wire_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint64> api2wire_opt_box_autoadd_u64(int? raw) {
    return raw == null ? ffi.nullptr : api2wire_box_autoadd_u64(raw);
  }

  @protected
  int api2wire_u64(int raw) {
    return raw;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire

  void _api_fill_to_wire_box_autoadd_cashu_transaction(
      CashuTransaction apiObj, ffi.Pointer<wire_CashuTransaction> wireObj) {
    _api_fill_to_wire_cashu_transaction(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_ln_transaction(
      LNTransaction apiObj, ffi.Pointer<wire_LNTransaction> wireObj) {
    _api_fill_to_wire_ln_transaction(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_message(
      Message apiObj, ffi.Pointer<wire_Message> wireObj) {
    _api_fill_to_wire_message(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_transaction(
      Transaction apiObj, ffi.Pointer<wire_Transaction> wireObj) {
    _api_fill_to_wire_transaction(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_cashu_transaction(
      CashuTransaction apiObj, wire_CashuTransaction wireObj) {
    wireObj.id = api2wire_opt_String(apiObj.id);
    _api_fill_to_wire_transaction_status(apiObj.status, wireObj.status);
    wireObj.time = api2wire_u64(apiObj.time);
    wireObj.amount = api2wire_u64(apiObj.amount);
    wireObj.mint = api2wire_String(apiObj.mint);
    wireObj.token = api2wire_String(apiObj.token);
    wireObj.from = api2wire_opt_String(apiObj.from);
  }

  void _api_fill_to_wire_ln_transaction(
      LNTransaction apiObj, wire_LNTransaction wireObj) {
    wireObj.id = api2wire_opt_String(apiObj.id);
    _api_fill_to_wire_transaction_status(apiObj.status, wireObj.status);
    wireObj.time = api2wire_u64(apiObj.time);
    wireObj.amount = api2wire_u64(apiObj.amount);
    wireObj.fee = api2wire_opt_box_autoadd_u64(apiObj.fee);
    wireObj.mint = api2wire_opt_String(apiObj.mint);
    wireObj.bolt11 = api2wire_String(apiObj.bolt11);
    wireObj.hash = api2wire_String(apiObj.hash);
  }

  void _api_fill_to_wire_message(Message apiObj, wire_Message wireObj) {
    if (apiObj is Message_Text) {
      var pre_direction = api2wire_direction(apiObj.direction);
      var pre_time = api2wire_u64(apiObj.time);
      var pre_content = api2wire_String(apiObj.content);
      wireObj.tag = 0;
      wireObj.kind = inner.inflate_Message_Text();
      wireObj.kind.ref.Text.ref.direction = pre_direction;
      wireObj.kind.ref.Text.ref.time = pre_time;
      wireObj.kind.ref.Text.ref.content = pre_content;
      return;
    }
    if (apiObj is Message_Invoice) {
      var pre_direction = api2wire_direction(apiObj.direction);
      var pre_time = api2wire_u64(apiObj.time);
      var pre_transaction_id = api2wire_String(apiObj.transactionId);
      wireObj.tag = 1;
      wireObj.kind = inner.inflate_Message_Invoice();
      wireObj.kind.ref.Invoice.ref.direction = pre_direction;
      wireObj.kind.ref.Invoice.ref.time = pre_time;
      wireObj.kind.ref.Invoice.ref.transaction_id = pre_transaction_id;
      return;
    }
    if (apiObj is Message_Token) {
      var pre_direction = api2wire_direction(apiObj.direction);
      var pre_time = api2wire_u64(apiObj.time);
      var pre_transaction_id = api2wire_String(apiObj.transactionId);
      wireObj.tag = 2;
      wireObj.kind = inner.inflate_Message_Token();
      wireObj.kind.ref.Token.ref.direction = pre_direction;
      wireObj.kind.ref.Token.ref.time = pre_time;
      wireObj.kind.ref.Token.ref.transaction_id = pre_transaction_id;
      return;
    }
  }

  void _api_fill_to_wire_transaction(
      Transaction apiObj, wire_Transaction wireObj) {
    if (apiObj is Transaction_CashuTransaction) {
      var pre_field0 = api2wire_box_autoadd_cashu_transaction(apiObj.field0);
      wireObj.tag = 0;
      wireObj.kind = inner.inflate_Transaction_CashuTransaction();
      wireObj.kind.ref.CashuTransaction.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is Transaction_LNTransaction) {
      var pre_field0 = api2wire_box_autoadd_ln_transaction(apiObj.field0);
      wireObj.tag = 1;
      wireObj.kind = inner.inflate_Transaction_LNTransaction();
      wireObj.kind.ref.LNTransaction.ref.field0 = pre_field0;
      return;
    }
  }

  void _api_fill_to_wire_transaction_status(
      TransactionStatus apiObj, wire_TransactionStatus wireObj) {
    if (apiObj is TransactionStatus_Sent) {
      wireObj.tag = 0;
      return;
    }
    if (apiObj is TransactionStatus_Received) {
      wireObj.tag = 1;
      return;
    }
    if (apiObj is TransactionStatus_Pending) {
      var pre_field0 = api2wire_pending(apiObj.field0);
      wireObj.tag = 2;
      wireObj.kind = inner.inflate_TransactionStatus_Pending();
      wireObj.kind.ref.Pending.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is TransactionStatus_Failed) {
      wireObj.tag = 3;
      return;
    }
    if (apiObj is TransactionStatus_Expired) {
      wireObj.tag = 4;
      return;
    }
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_init_db(
    int port_,
    ffi.Pointer<wire_uint_8_list> storage_path,
  ) {
    return _wire_init_db(
      port_,
      storage_path,
    );
  }

  late final _wire_init_dbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_init_db');
  late final _wire_init_db = _wire_init_dbPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_init_nostr(
    int port_,
    ffi.Pointer<wire_uint_8_list> storage_path,
    ffi.Pointer<wire_uint_8_list> private_key,
  ) {
    return _wire_init_nostr(
      port_,
      storage_path,
      private_key,
    );
  }

  late final _wire_init_nostrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_init_nostr');
  late final _wire_init_nostr = _wire_init_nostrPtr.asFunction<
      void Function(
          int, ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_get_keys(
    int port_,
  ) {
    return _wire_get_keys(
      port_,
    );
  }

  late final _wire_get_keysPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_keys');
  late final _wire_get_keys =
      _wire_get_keysPtr.asFunction<void Function(int)>();

  void wire_nostr_logout(
    int port_,
  ) {
    return _wire_nostr_logout(
      port_,
    );
  }

  late final _wire_nostr_logoutPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_nostr_logout');
  late final _wire_nostr_logout =
      _wire_nostr_logoutPtr.asFunction<void Function(int)>();

  void wire_get_relays(
    int port_,
  ) {
    return _wire_get_relays(
      port_,
    );
  }

  late final _wire_get_relaysPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_relays');
  late final _wire_get_relays =
      _wire_get_relaysPtr.asFunction<void Function(int)>();

  void wire_add_relay(
    int port_,
    ffi.Pointer<wire_uint_8_list> relay,
  ) {
    return _wire_add_relay(
      port_,
      relay,
    );
  }

  late final _wire_add_relayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_add_relay');
  late final _wire_add_relay = _wire_add_relayPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_remove_relay(
    int port_,
    ffi.Pointer<wire_uint_8_list> relay,
  ) {
    return _wire_remove_relay(
      port_,
      relay,
    );
  }

  late final _wire_remove_relayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_remove_relay');
  late final _wire_remove_relay = _wire_remove_relayPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_fetch_contacts(
    int port_,
    ffi.Pointer<wire_uint_8_list> pubkey,
  ) {
    return _wire_fetch_contacts(
      port_,
      pubkey,
    );
  }

  late final _wire_fetch_contactsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_fetch_contacts');
  late final _wire_fetch_contacts = _wire_fetch_contactsPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_add_contact(
    int port_,
    ffi.Pointer<wire_uint_8_list> pubkey,
  ) {
    return _wire_add_contact(
      port_,
      pubkey,
    );
  }

  late final _wire_add_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_add_contact');
  late final _wire_add_contact = _wire_add_contactPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_remove_contact(
    int port_,
    ffi.Pointer<wire_uint_8_list> pubkey,
  ) {
    return _wire_remove_contact(
      port_,
      pubkey,
    );
  }

  late final _wire_remove_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_remove_contact');
  late final _wire_remove_contact = _wire_remove_contactPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_get_contacts(
    int port_,
  ) {
    return _wire_get_contacts(
      port_,
    );
  }

  late final _wire_get_contactsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_contacts');
  late final _wire_get_contacts =
      _wire_get_contactsPtr.asFunction<void Function(int)>();

  void wire_get_contact_picture_id(
    int port_,
    ffi.Pointer<wire_uint_8_list> pubkey,
  ) {
    return _wire_get_contact_picture_id(
      port_,
      pubkey,
    );
  }

  late final _wire_get_contact_picture_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_get_contact_picture_id');
  late final _wire_get_contact_picture_id = _wire_get_contact_picture_idPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_fetch_picture(
    int port_,
    ffi.Pointer<wire_uint_8_list> url,
  ) {
    return _wire_fetch_picture(
      port_,
      url,
    );
  }

  late final _wire_fetch_picturePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_fetch_picture');
  late final _wire_fetch_picture = _wire_fetch_picturePtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_send_message(
    int port_,
    ffi.Pointer<wire_uint_8_list> pubkey,
    ffi.Pointer<wire_Message> message,
  ) {
    return _wire_send_message(
      port_,
      pubkey,
      message,
    );
  }

  late final _wire_send_messagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_Message>)>>('wire_send_message');
  late final _wire_send_message = _wire_send_messagePtr.asFunction<
      void Function(
          int, ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_Message>)>();

  void wire_get_conversation(
    int port_,
    ffi.Pointer<wire_uint_8_list> pubkey,
  ) {
    return _wire_get_conversation(
      port_,
      pubkey,
    );
  }

  late final _wire_get_conversationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_get_conversation');
  late final _wire_get_conversation = _wire_get_conversationPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_get_balances(
    int port_,
  ) {
    return _wire_get_balances(
      port_,
    );
  }

  late final _wire_get_balancesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_balances');
  late final _wire_get_balances =
      _wire_get_balancesPtr.asFunction<void Function(int)>();

  void wire_add_mint(
    int port_,
    ffi.Pointer<wire_uint_8_list> url,
  ) {
    return _wire_add_mint(
      port_,
      url,
    );
  }

  late final _wire_add_mintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_add_mint');
  late final _wire_add_mint = _wire_add_mintPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_get_wallets(
    int port_,
  ) {
    return _wire_get_wallets(
      port_,
    );
  }

  late final _wire_get_walletsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_wallets');
  late final _wire_get_wallets =
      _wire_get_walletsPtr.asFunction<void Function(int)>();

  void wire_remove_wallet(
    int port_,
    ffi.Pointer<wire_uint_8_list> url,
  ) {
    return _wire_remove_wallet(
      port_,
      url,
    );
  }

  late final _wire_remove_walletPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_remove_wallet');
  late final _wire_remove_wallet = _wire_remove_walletPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_check_spendable(
    int port_,
    ffi.Pointer<wire_Transaction> transaction,
  ) {
    return _wire_check_spendable(
      port_,
      transaction,
    );
  }

  late final _wire_check_spendablePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_Transaction>)>>('wire_check_spendable');
  late final _wire_check_spendable = _wire_check_spendablePtr
      .asFunction<void Function(int, ffi.Pointer<wire_Transaction>)>();

  void wire_receive_token(
    int port_,
    ffi.Pointer<wire_uint_8_list> encoded_token,
  ) {
    return _wire_receive_token(
      port_,
      encoded_token,
    );
  }

  late final _wire_receive_tokenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_receive_token');
  late final _wire_receive_token = _wire_receive_tokenPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_send(
    int port_,
    int amount,
    ffi.Pointer<wire_uint_8_list> active_mint,
  ) {
    return _wire_send(
      port_,
      amount,
      active_mint,
    );
  }

  late final _wire_sendPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Uint64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_send');
  late final _wire_send = _wire_sendPtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_request_mint(
    int port_,
    int amount,
    ffi.Pointer<wire_uint_8_list> mint_url,
  ) {
    return _wire_request_mint(
      port_,
      amount,
      mint_url,
    );
  }

  late final _wire_request_mintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Uint64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_request_mint');
  late final _wire_request_mint = _wire_request_mintPtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_mint_token(
    int port_,
    int amount,
    ffi.Pointer<wire_uint_8_list> hash,
    ffi.Pointer<wire_uint_8_list> mint,
  ) {
    return _wire_mint_token(
      port_,
      amount,
      hash,
      mint,
    );
  }

  late final _wire_mint_tokenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64,
              ffi.Uint64,
              ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_mint_token');
  late final _wire_mint_token = _wire_mint_tokenPtr.asFunction<
      void Function(int, int, ffi.Pointer<wire_uint_8_list>,
          ffi.Pointer<wire_uint_8_list>)>();

  void wire_mint_swap(
    int port_,
    ffi.Pointer<wire_uint_8_list> from_mint,
    ffi.Pointer<wire_uint_8_list> to_mint,
    int amount,
  ) {
    return _wire_mint_swap(
      port_,
      from_mint,
      to_mint,
      amount,
    );
  }

  late final _wire_mint_swapPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>, ffi.Uint64)>>('wire_mint_swap');
  late final _wire_mint_swap = _wire_mint_swapPtr.asFunction<
      void Function(int, ffi.Pointer<wire_uint_8_list>,
          ffi.Pointer<wire_uint_8_list>, int)>();

  void wire_melt(
    int port_,
    int amount,
    ffi.Pointer<wire_uint_8_list> invoice,
    ffi.Pointer<wire_uint_8_list> mint,
  ) {
    return _wire_melt(
      port_,
      amount,
      invoice,
      mint,
    );
  }

  late final _wire_meltPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64,
              ffi.Uint64,
              ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_melt');
  late final _wire_melt = _wire_meltPtr.asFunction<
      void Function(int, int, ffi.Pointer<wire_uint_8_list>,
          ffi.Pointer<wire_uint_8_list>)>();

  void wire_decode_invoice(
    int port_,
    ffi.Pointer<wire_uint_8_list> encoded_invoice,
  ) {
    return _wire_decode_invoice(
      port_,
      encoded_invoice,
    );
  }

  late final _wire_decode_invoicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_decode_invoice');
  late final _wire_decode_invoice = _wire_decode_invoicePtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_get_transactions(
    int port_,
  ) {
    return _wire_get_transactions(
      port_,
    );
  }

  late final _wire_get_transactionsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_transactions');
  late final _wire_get_transactions =
      _wire_get_transactionsPtr.asFunction<void Function(int)>();

  void wire_get_inbox(
    int port_,
  ) {
    return _wire_get_inbox(
      port_,
    );
  }

  late final _wire_get_inboxPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_inbox');
  late final _wire_get_inbox =
      _wire_get_inboxPtr.asFunction<void Function(int)>();

  void wire_redeam_inbox(
    int port_,
  ) {
    return _wire_redeam_inbox(
      port_,
    );
  }

  late final _wire_redeam_inboxPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_redeam_inbox');
  late final _wire_redeam_inbox =
      _wire_redeam_inboxPtr.asFunction<void Function(int)>();

  void wire_get_transaction(
    int port_,
    ffi.Pointer<wire_uint_8_list> tid,
  ) {
    return _wire_get_transaction(
      port_,
      tid,
    );
  }

  late final _wire_get_transactionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_get_transaction');
  late final _wire_get_transaction = _wire_get_transactionPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_get_mints(
    int port_,
  ) {
    return _wire_get_mints(
      port_,
    );
  }

  late final _wire_get_mintsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_mints');
  late final _wire_get_mints =
      _wire_get_mintsPtr.asFunction<void Function(int)>();

  void wire_get_mint_information(
    int port_,
    ffi.Pointer<wire_uint_8_list> mint,
  ) {
    return _wire_get_mint_information(
      port_,
      mint,
    );
  }

  late final _wire_get_mint_informationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_get_mint_information');
  late final _wire_get_mint_information = _wire_get_mint_informationPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_get_active_mint(
    int port_,
  ) {
    return _wire_get_active_mint(
      port_,
    );
  }

  late final _wire_get_active_mintPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_active_mint');
  late final _wire_get_active_mint =
      _wire_get_active_mintPtr.asFunction<void Function(int)>();

  void wire_set_active_mint(
    int port_,
    ffi.Pointer<wire_uint_8_list> mint_url,
  ) {
    return _wire_set_active_mint(
      port_,
      mint_url,
    );
  }

  late final _wire_set_active_mintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_set_active_mint');
  late final _wire_set_active_mint = _wire_set_active_mintPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_decode_token(
    int port_,
    ffi.Pointer<wire_uint_8_list> encoded_token,
  ) {
    return _wire_decode_token(
      port_,
      encoded_token,
    );
  }

  late final _wire_decode_tokenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_decode_token');
  late final _wire_decode_token = _wire_decode_tokenPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  ffi.Pointer<wire_CashuTransaction> new_box_autoadd_cashu_transaction_0() {
    return _new_box_autoadd_cashu_transaction_0();
  }

  late final _new_box_autoadd_cashu_transaction_0Ptr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_CashuTransaction> Function()>>(
      'new_box_autoadd_cashu_transaction_0');
  late final _new_box_autoadd_cashu_transaction_0 =
      _new_box_autoadd_cashu_transaction_0Ptr
          .asFunction<ffi.Pointer<wire_CashuTransaction> Function()>();

  ffi.Pointer<wire_LNTransaction> new_box_autoadd_ln_transaction_0() {
    return _new_box_autoadd_ln_transaction_0();
  }

  late final _new_box_autoadd_ln_transaction_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_LNTransaction> Function()>>(
          'new_box_autoadd_ln_transaction_0');
  late final _new_box_autoadd_ln_transaction_0 =
      _new_box_autoadd_ln_transaction_0Ptr
          .asFunction<ffi.Pointer<wire_LNTransaction> Function()>();

  ffi.Pointer<wire_Message> new_box_autoadd_message_0() {
    return _new_box_autoadd_message_0();
  }

  late final _new_box_autoadd_message_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_Message> Function()>>(
          'new_box_autoadd_message_0');
  late final _new_box_autoadd_message_0 = _new_box_autoadd_message_0Ptr
      .asFunction<ffi.Pointer<wire_Message> Function()>();

  ffi.Pointer<wire_Transaction> new_box_autoadd_transaction_0() {
    return _new_box_autoadd_transaction_0();
  }

  late final _new_box_autoadd_transaction_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_Transaction> Function()>>(
          'new_box_autoadd_transaction_0');
  late final _new_box_autoadd_transaction_0 = _new_box_autoadd_transaction_0Ptr
      .asFunction<ffi.Pointer<wire_Transaction> Function()>();

  ffi.Pointer<ffi.Uint64> new_box_autoadd_u64_0(
    int value,
  ) {
    return _new_box_autoadd_u64_0(
      value,
    );
  }

  late final _new_box_autoadd_u64_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint64> Function(ffi.Uint64)>>(
          'new_box_autoadd_u64_0');
  late final _new_box_autoadd_u64_0 = _new_box_autoadd_u64_0Ptr
      .asFunction<ffi.Pointer<ffi.Uint64> Function(int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  ffi.Pointer<MessageKind> inflate_Message_Text() {
    return _inflate_Message_Text();
  }

  late final _inflate_Message_TextPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<MessageKind> Function()>>(
          'inflate_Message_Text');
  late final _inflate_Message_Text = _inflate_Message_TextPtr
      .asFunction<ffi.Pointer<MessageKind> Function()>();

  ffi.Pointer<MessageKind> inflate_Message_Invoice() {
    return _inflate_Message_Invoice();
  }

  late final _inflate_Message_InvoicePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<MessageKind> Function()>>(
          'inflate_Message_Invoice');
  late final _inflate_Message_Invoice = _inflate_Message_InvoicePtr
      .asFunction<ffi.Pointer<MessageKind> Function()>();

  ffi.Pointer<MessageKind> inflate_Message_Token() {
    return _inflate_Message_Token();
  }

  late final _inflate_Message_TokenPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<MessageKind> Function()>>(
          'inflate_Message_Token');
  late final _inflate_Message_Token = _inflate_Message_TokenPtr
      .asFunction<ffi.Pointer<MessageKind> Function()>();

  ffi.Pointer<TransactionKind> inflate_Transaction_CashuTransaction() {
    return _inflate_Transaction_CashuTransaction();
  }

  late final _inflate_Transaction_CashuTransactionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<TransactionKind> Function()>>(
          'inflate_Transaction_CashuTransaction');
  late final _inflate_Transaction_CashuTransaction =
      _inflate_Transaction_CashuTransactionPtr
          .asFunction<ffi.Pointer<TransactionKind> Function()>();

  ffi.Pointer<TransactionKind> inflate_Transaction_LNTransaction() {
    return _inflate_Transaction_LNTransaction();
  }

  late final _inflate_Transaction_LNTransactionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<TransactionKind> Function()>>(
          'inflate_Transaction_LNTransaction');
  late final _inflate_Transaction_LNTransaction =
      _inflate_Transaction_LNTransactionPtr
          .asFunction<ffi.Pointer<TransactionKind> Function()>();

  ffi.Pointer<TransactionStatusKind> inflate_TransactionStatus_Pending() {
    return _inflate_TransactionStatus_Pending();
  }

  late final _inflate_TransactionStatus_PendingPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<TransactionStatusKind> Function()>>(
      'inflate_TransactionStatus_Pending');
  late final _inflate_TransactionStatus_Pending =
      _inflate_TransactionStatus_PendingPtr
          .asFunction<ffi.Pointer<TransactionStatusKind> Function()>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_Message_Text extends ffi.Struct {
  @ffi.Int32()
  external int direction;

  @ffi.Uint64()
  external int time;

  external ffi.Pointer<wire_uint_8_list> content;
}

final class wire_Message_Invoice extends ffi.Struct {
  @ffi.Int32()
  external int direction;

  @ffi.Uint64()
  external int time;

  external ffi.Pointer<wire_uint_8_list> transaction_id;
}

final class wire_Message_Token extends ffi.Struct {
  @ffi.Int32()
  external int direction;

  @ffi.Uint64()
  external int time;

  external ffi.Pointer<wire_uint_8_list> transaction_id;
}

final class MessageKind extends ffi.Union {
  external ffi.Pointer<wire_Message_Text> Text;

  external ffi.Pointer<wire_Message_Invoice> Invoice;

  external ffi.Pointer<wire_Message_Token> Token;
}

final class wire_Message extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ffi.Pointer<MessageKind> kind;
}

final class wire_TransactionStatus_Sent extends ffi.Opaque {}

final class wire_TransactionStatus_Received extends ffi.Opaque {}

final class wire_TransactionStatus_Pending extends ffi.Struct {
  @ffi.Int32()
  external int field0;
}

final class wire_TransactionStatus_Failed extends ffi.Opaque {}

final class wire_TransactionStatus_Expired extends ffi.Opaque {}

final class TransactionStatusKind extends ffi.Union {
  external ffi.Pointer<wire_TransactionStatus_Sent> Sent;

  external ffi.Pointer<wire_TransactionStatus_Received> Received;

  external ffi.Pointer<wire_TransactionStatus_Pending> Pending;

  external ffi.Pointer<wire_TransactionStatus_Failed> Failed;

  external ffi.Pointer<wire_TransactionStatus_Expired> Expired;
}

final class wire_TransactionStatus extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ffi.Pointer<TransactionStatusKind> kind;
}

final class wire_CashuTransaction extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> id;

  external wire_TransactionStatus status;

  @ffi.Uint64()
  external int time;

  @ffi.Uint64()
  external int amount;

  external ffi.Pointer<wire_uint_8_list> mint;

  external ffi.Pointer<wire_uint_8_list> token;

  external ffi.Pointer<wire_uint_8_list> from;
}

final class wire_Transaction_CashuTransaction extends ffi.Struct {
  external ffi.Pointer<wire_CashuTransaction> field0;
}

final class wire_LNTransaction extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> id;

  external wire_TransactionStatus status;

  @ffi.Uint64()
  external int time;

  @ffi.Uint64()
  external int amount;

  external ffi.Pointer<ffi.Uint64> fee;

  external ffi.Pointer<wire_uint_8_list> mint;

  external ffi.Pointer<wire_uint_8_list> bolt11;

  external ffi.Pointer<wire_uint_8_list> hash;
}

final class wire_Transaction_LNTransaction extends ffi.Struct {
  external ffi.Pointer<wire_LNTransaction> field0;
}

final class TransactionKind extends ffi.Union {
  external ffi.Pointer<wire_Transaction_CashuTransaction> CashuTransaction;

  external ffi.Pointer<wire_Transaction_LNTransaction> LNTransaction;
}

final class wire_Transaction extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ffi.Pointer<TransactionKind> kind;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
